from django.db import models

# Create your models here.
from django.utils import timezone


class ActiveProjectManager(models.Manager):
    """
    Custom manager that automatically filters out soft-deleted projects.
    This means Project.objects.all() will only return active projects.
    """

    def get_queryset(self):
        return super().get_queryset().filter(deleted_at__isnull=True)


class Project(models.Model):
    # ID is automatically generated by Django (BigAutoField)
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True)

    # Managers
    objects = ActiveProjectManager()  # The default manager hides deleted items
    all_objects = models.Manager()  # Use Project.all_objects.all() to see everything including deleted

    class Meta:
        ordering = ['-created_at']

    def delete(self, *args, **kwargs):
        """Override the default delete method to perform a soft delete."""
        self.deleted_at = timezone.now()
        self.save()

    def restore(self):
        """Helper method to easily restore a soft-deleted project."""
        self.deleted_at = None
        self.save()

    def hard_delete(self, *args, **kwargs):
        """Keep a way to actually remove the record from the database if ever needed."""
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name